version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8200:8200"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - external
    container_name: efserver
    hostname: "efserver"
    tty: true
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1
  aws:
    image: "electricflow/awscli:latest"
    ports:
      - "7808:7808"
    networks:
      - external
    container_name: awscli
    hostname: "awscli"
    tty: true
    extra_hosts:
      - maven.org:127.0.0.1
      - repo1.maven.org:127.0.0.1
      - jcenter.bintray.com:127.0.0.1

networks:
  external:
    driver: bridge
